socket_path = "/run/onkyoctl/onkyoctl.sock"

serial_device = "/dev/serial/by-id/usb-Arduino_Nano_OnkyoRI-if00-port0"
serial_baud = 115200
serial_open_delay_ms = 7000

wake_codes = ["0x02F"]
wake_gap_ms = 1000

power_off_codes = ["0x0DA"]
power_off_gap_ms = 250

power_off_delay_seconds = 120

wake_on_bluetooth_connect = true
wake_on_playback_start = true

bluetooth_use_transport_state = true
